### ISSUE TITLE
Panics from recent merge

### ISSUE THREAD

**Issue by jefferai** [mitchellh/copystructure#25]
Bisecting has shown that that c35361eaffbd8150818d8d8c6adadcd056b2229a is the direct cause of https://travis-ci.org/hashicorp/vault/builds/196599401

**Comment by mitchellh** [comment]
![2017-01-30 at 8 27 am](https://cloud.githubusercontent.com/assets/1299/22431335/05b21e12-e6c6-11e6-94a5-6862214a6b77.png)

Solved. 💃
