### ISSUE TITLE
Copy cannot copy a struct having *time.Time field defined

### ISSUE THREAD

**Issue by StanislavBelyakov** [mitchellh/copystructure#26]
The following code panics during the runtime:
```
	type Test struct {
		Now *time.Time
	}

	now := time.Now()
	test := Test{
		Now: &now,
	}
	copystructure.Copy(test)
```
Message:
 `reflect.Set: value of type time.Time is not assignable to type *time.Time`

I suspect the root of the issue is within [func (w *walker) Struct](https://github.com/mitchellh/copystructure/blob/master/copystructure.go#L358) method. When `Copiers` is used, `v` holds the concrete value. However, for other cases `v` is a pointer to concrete value. This inconsistency leads to the problem described above.

**Comment by mitchellh** [comment]
Thanks! I have a fix in a PR...
