### ISSUE TITLE
Not copying type alias properly

### ISSUE THREAD

**Issue by yulrizka** [mitchellh/copystructure#37]
When a type is aliased, it doesn't copy the type correctly

https://play.golang.org/p/3vuXlS75wJx

```golang
package main

import (
	"fmt"
	"github.com/mitchellh/copystructure"
	"time"
)

type Date time.Time

func main() {
	now := time.Now()
	d := Date(now)
	fmt.Printf("now = %+v\n", now) // now = 2009-11-10 23:00:00 +0000 UTC m=+0.000000001
	fmt.Printf("d = %+v\n", d)     // d = {wall:13454110244426743808 ext:1 loc:0x572620}

	// time clone
	nowClone := copystructure.Must(copystructure.Copy(now))
	now2 := nowClone.(time.Time)
	fmt.Printf("now2 = %+v\n", now2) // now2 = 2009-11-10 23:00:00 +0000 UTC m=+0.000000001

	// alias clone
	d2Clone := copystructure.Must(copystructure.Copy(d))
	d2 := d2Clone.(Date)
	fmt.Printf("d2 = %+v\n", d2) // d2 = {wall:0 ext:0 loc:<nil>}
}
```

**Comment by mitchellh** [comment]
`type Data time.Time` creates a _new type_ and **not** an alias. The alias syntax in Go is `type A = B`. If you did `type Date = time.Time`, then it works.

Therefore, copystructure doesn't know how to decode a `Date`. You'll have to setup a new custom copier for that (it is trivial, see: https://github.com/mitchellh/copystructure/blob/master/copier_time.go).
